
-- Generated by ORDS REST Data Services 25.4.0.r3641739
-- Schema: WKSP_WSUTHAMAN  Date: Fri Mar 06 05:12:01 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wsuthaman',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'authend',
      p_base_path      => '/authend/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'authend',
      p_pattern        => 'get-token',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'authend',
      p_pattern        => 'get-token',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_token           VARCHAR2 (4000);
    v_is_user_exists  NUMBER;
    v_username        VARCHAR2(200);
    v_user_role       VARCHAR2(200);
BEGIN

 SELECT COUNT (user_name)
      INTO v_is_user_exists
      FROM user_master
     WHERE LOWER(user_name) = LOWER(:username);

       IF v_is_user_exists <= 0
    THEN
        APEX_JSON.open_object;
        APEX_JSON.write (''message'', ''User doesnt exist'');
        APEX_JSON.close_object;
        RETURN;
    END IF;
v_token :=
        apex_jwt.encode (
            p_iss       => ''ORDS'',
            p_sub       => :username,--''uthaman'',
            p_aud       => ''ADMIN'',
            p_iat_ts    => SYSDATE,
            p_exp_sec   => 60 * 5,
            p_signature_key   =>
                sys.UTL_RAW.cast_to_raw (
                    ''secretKey''));
    apex_json.open_object;
    APEX_JSON.write (''token'', v_token);
    APEX_JSON.write (''message'', ''Access token generated successfully'');
    APEX_JSON.cl' || 'ose_object;

EXCEPTION
    WHEN OTHERS
    THEN
        APEX_JSON.open_object;
        APEX_JSON.write (''message'', ''Error'');
        APEX_JSON.close_object;
        :status := 401;
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'authend',
      p_pattern            => 'get-token',
      p_method             => 'POST',
      p_name               => 'username',
      p_bind_variable_name => 'username',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'username');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'authend',
      p_pattern        => 'validate-token',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'authend',
      p_pattern        => 'validate-token',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_token            APEX_JWT.T_TOKEN;
    l_user_object      APEX_JSON.T_VALUES;
    l_header_value     VARCHAR2(4000);
    l_bearer_token     VARCHAR2(4000);
    l_scope            VARCHAR2(200);
BEGIN
l_header_value := OWA_UTIL.get_cgi_env(''Authorization'');
 IF l_header_value IS NOT NULL AND INSTR(l_header_value, ''Bearer '') = 1 THEN
        -- Extract the token part after ''Bearer ''
        l_bearer_token := SUBSTR(l_header_value, 8);
    ELSE
        --return error message in json format if the token is not founded
        APEX_JSON.open_object;
        APEX_JSON.write (''message'', ''Error no token found'');
        APEX_JSON.close_object;
        :status := 401;
        RETURN;
    END IF;
        l_token :=
        apex_jwt.DECODE (
            p_value   => l_bearer_token,
            p_signature_key   =>sys.utl_raw.cast_to_raw(''secretKey''));
        APEX_JSON.open_object;
        APEX_JSON.write (''message'', ''Token is valid'');
        APEX_JSON.clos' || 'e_object;
end;');


COMMIT;

END;